name: meu_ajudante_fg
description: Meu Ajudante (FG ElÃ©trica) - offline first
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  crypto: ^3.0.3

  barcode: ^2.2.4

  image_picker: ^1.2.1
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.14.2
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  signature: ^6.3.0
  url_launcher: ^6.3.2
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  open_filex: ^4.7.0
  supabase_flutter: ^2.12.0
  uuid: ^4.5.2
  csv: ^6.0.0
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/images/

flutter_launcher_icons:
  android: true
  linux: true

  windows:
    generate: true
    image_path: "assets/icon.png"


  image_path: "assets/icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon.png"

